output: docs
author: gematik Gesellschaft für Telematikanwendungen der Gesundheitskarte mbH
author_url: http://www.gematik.de
exclude: /*/internal*
module: GemCommonsKit
github_url: http://www.github.com/gematik/ref-GemCommonsKit.git
theme: jony
xcodebuild_arguments:
- "-project"
- 'GemCommonsKit.xcodeproj'
